### PR TITLE
Fix CI : retrieving dependencies

### PR DESCRIPTION
**Pull request by valnoel**
To retrieve libogg and libvorbis from the repository

### CODE REVIEW

**Review by MarcAntoine-Arnaud — COMMENTED** [review]
AppVeyor build is broken as wget is not installed.
Curl in installed by default on all platforms, more generic...

**Comment by valnoel** [comment]
@MarcAntoine-Arnaud 
`wget` is not used into AppVeyor currently, only on Travis, but it seems we have the same problem on both platform with `curl`, which does not complete the archives download.
`wget` seems to resolve the problem for Travis, but we have find another solution for AppVeyor... (so I switch this PR in WIP) :)

Thanks for the review, by the way. ;)

**Comment by MarcAntoine-Arnaud** [comment]
Okay, it seems AppVeyor was already broken before your PR.
I think we need to fix AppVeyor build before merge it.

**Comment by valnoel** [comment]
OK, actually for __AppVeyor__, the problem does not seems to come from `curl` but from the URL to FFmpeg, that return a 404 Not Found status. Indeed, there is no more __ffmpeg-2.4.5-win32-dev.7z__ into the [repository](http://ffmpeg.zeranoe.com/builds/win32/dev). Do you have any idea of where we could find a new repository?

On __Travis__ we could keep `curl` using a `-L` option, and piping the response into a file : 
```
$ curl -OL http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.4.tar.gz > libvorbis-1.3.4.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   460  100   460    0     0   1429      0 --:--:-- --:--:-- --:--:--  1428
100   442  100   442    0     0     42      0  0:00:10  0:00:10 --:--:--   891
100 1593k  100 1593k    0     0   133k      0  0:00:11  0:00:11 --:--:-- 1962k
```
@MarcAntoine-Arnaud  Would it be better according to you ?

**Comment by MarcAntoine-Arnaud** [comment]
This PR is okay for me, I think we can merge instead of AppVeyor build still broken.

To fix AppVeyor, it means we need to support FFMpeg > 3.0 (#252)

**Comment by valnoel** [comment]
OK then! I cannot find any another repository with FFmpeg Windows builds... I create a new issue for this: https://github.com/avTranscoder/avTranscoder/issues/302
@cchampet OK for you?

**Comment by cchampet** [comment]
Thank you gentlemen ;)
Indeed, to fix AppVeyor, we will have to to support FFMpeg > 3.0...

**Review by cchampet — COMMENTED** [review]
LGTM

**Pull request merged**
